### ISSUE TITLE
Error when closing server

### ISSUE THREAD

**Issue by CardboardBread** [qwertysam/afroman-client#13]
Exception in thread "Client/Server/Game" java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at ca.afroman.d.a.b(Unknown Source)
    at ca.afroman.o.d.b(Unknown Source)
    at ca.afroman.p.b.a(Unknown Source)
    at ca.afroman.p.a.run(Unknown Source)

does not seem to impact function of program, but is easily reproducible

**Comment by defaultsamson** [comment]
Start server from client, then stop server

[2016-09-05/11:55:16] [Client/Server/Game] [DEBUG] Stopping Thread
[2016-09-05/11:55:16] [Client/Receive(127.0.0.1:2143)] [DEBUG] Stopping Thread
[2016-09-05/11:55:16] [Client/Receive] [DEBUG] Stopping Thread
[2016-09-05/11:55:16] [Client/Send] [DEBUG] Stopping Thread
[2016-09-05/11:55:18] [Client/Server/Receive(127.0.0.1:48526)] [DEBUG] Stopping Thread
[2016-09-05/11:55:18] [Client/Server/Receive] [DEBUG] Stopping Thread
[2016-09-05/11:55:18] [Client/Server/Send] [DEBUG] Stopping Thread
[2016-09-05/11:55:18] [Client/Server/Receive] [DEBUG] Stopping Thread
[2016-09-05/11:55:18] [Client/Server/Send] [DEBUG] Stopping Thread
Exception in thread "Client/Server/Game" java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at ca.afroman.game.Game.tick(Game.java:178)
    at ca.afroman.server.ServerGame.tick(ServerGame.java:814)
    at ca.afroman.thread.DynamicTickRenderThread.onRun(DynamicTickRenderThread.java:45)
    at ca.afroman.thread.DynamicThread.run(DynamicThread.java:90)
