### ISSUE TITLE
Something is not reading data, i dont know what

### ISSUE THREAD

**Issue by CardboardBread** [qwertysam/afroman-client#21]
[2016-11-21/23:37:10] [Client/Game] [DEBUG] Initializing external console output...
[2016-11-21/23:37:10] [Client/Game] [DEBUG] Initializing logging streams...
[2016-11-21/23:37:10] [Client/Game] [DEBUG] Creating environment... (2016.10.5)
[2016-11-21/23:37:11] [Client/Game] [DEBUG] Loading game...
[2016-11-21/23:37:11] [Client/Game] [DEBUG] Loading options...
[2016-11-21/23:37:11] [Client/Loading-Display] [DEBUG] Starting Thread
[2016-11-21/23:37:11] [Client/Game] [DEBUG] Loading assets...
[2016-11-21/23:37:11] [DEBUG] Disribution uses WAV audio files
[2016-11-21/23:37:11] [Client/Game] [DEBUG] Initializing game variables...
[2016-11-21/23:37:11] [Client/Game] [DEBUG] Disposing of loading screen...
[2016-11-21/23:37:11] [Client/Loading-Display] [DEBUG] Stopping Thread
[2016-11-21/23:37:11] [Client/Game] [DEBUG] Game loaded. Took 0.393 seconds
[2016-11-21/23:37:11] [Client/Game] [DEBUG] Starting Thread
[2016-11-21/23:37:12] [Client/Server/Receive] [DEBUG] Starting Thread
[2016-11-21/23:37:12] [Client/Server/Send] [DEBUG] Starting Thread
[2016-11-21/23:37:12] [Client/Server/Game] [DEBUG] Server connected on 127.0.0.1:2143
[2016-11-21/23:37:12] [Client/Server/Game] [DEBUG] Starting Thread
[2016-11-21/23:37:12] [Client/Receive] [DEBUG] Starting Thread
[2016-11-21/23:37:12] [Client/Send] [DEBUG] Starting Thread
[2016-11-21/23:37:12] [Client/Send] [DEBUG] [127.0.0.1:2143] REQUEST_CONNECTION
[2016-11-21/23:37:12] [Client/Server/Receive] [DEBUG] [127.0.0.1:50410] REQUEST_CONNECTION
[2016-11-21/23:37:12] [Client/Server/Send] [DEBUG] [127.0.0.1:50410] ASSIGN_CLIENTID
[2016-11-21/23:37:12] [Client/Receive] [DEBUG] [127.0.0.1:2143] ASSIGN_CLIENTID
[2016-11-21/23:37:12] [Client/Server/Send] [DEBUG] [127.0.0.1:50410] UPDATE_PLAYERLIST
[2016-11-21/23:37:12] [Client/Server/Receive(127.0.0.1:14126)] [DEBUG] Starting Thread
[2016-11-21/23:37:12] [Client/Receive] [DEBUG] [127.0.0.1:2143] UPDATE_PLAYERLIST
[2016-11-21/23:37:12] [Client/Receive(127.0.0.1:2143)] [DEBUG] Starting Thread
[2016-11-21/23:37:12] [Client/Server/Game] [DEBUG] Accepted client in a blocking format
[2016-11-21/23:37:14] [Client/Server/Send] [DEBUG] [127.0.0.1:50410] TEST_PING
[2016-11-21/23:37:14] [Client/Receive] [DEBUG] [127.0.0.1:2143] TEST_PING
[2016-11-21/23:37:14] [Client/Send] [DEBUG] [127.0.0.1:2143] TEST_PING
[2016-11-21/23:37:14] [Client/Server/Receive] [DEBUG] [127.0.0.1:50410] TEST_PING
[2016-11-21/23:37:16] [Client/Server/Send] [DEBUG] [127.0.0.1:50410] TEST_PING
[2016-11-21/23:37:16] [Client/Receive] [DEBUG] [127.0.0.1:2143] TEST_PING
[2016-11-21/23:37:16] [Client/Send] [DEBUG] [127.0.0.1:2143] TEST_PING
[2016-11-21/23:37:16] [Client/Server/Receive] [DEBUG] [127.0.0.1:50410] TEST_PING
[2016-11-21/23:37:18] [Client/Server/Send] [DEBUG] [127.0.0.1:50410] TEST_PING
[2016-11-21/23:37:18] [Client/Receive] [DEBUG] [127.0.0.1:2143] TEST_PING
[2016-11-21/23:37:18] [Client/Send] [DEBUG] [127.0.0.1:2143] TEST_PING
[2016-11-21/23:37:18] [Client/Server/Receive] [DEBUG] [127.0.0.1:50410] TEST_PING
[2016-11-21/23:37:20] [Client/Send] [DEBUG] [127.0.0.1:2143] START_SERVER
Write: [9 0 ]
Read: [9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 Write: [0 9 0 ]
0 ]
Get: [9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ]
[2016-11-21/23:37:20] [Client/Server/Receive(127.0.0.1:14126)] [DEBUG] [127.0.0.1:14126] START_SERVER
Write: [9 0 ]
Read: [9 0 9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ]
[2016-11-21/23:37:20] [Client/Server/Game] [DEBUG] Stopping Thread
[2016-11-21/23:37:20] [Client/Server/Send] [DEBUG] [127.0.0.1:50410] START_SERVER
Get: [9 0 9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ]
[2016-11-21/23:37:20] [Client/Server/Receive(127.0.0.1:14126)] [DEBUG] [127.0.0.1:14126] START_SERVER
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
Write: [9 0 ]
[2016-11-21/23:37:20] [Client/Server/Receive(127.0.0.1:14126)] [DEBUG] Stopping Thread
[2016-11-21/23:37:20] [Client/Server/Receive] [DEBUG] Stopping Thread
[2016-11-21/23:37:20] [Client/Server/Send] [DEBUG] Stopping Thread
java.net.SocketException: socket closed
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:145)
	at java.net.DatagramSocket.receive(DatagramSocket.java:725)
	at ca.afroman.game.PacketReceiver.onRun(PacketReceiver.java:45)
	at ca.afroman.thread.DynamicThread.dynamicRun(DynamicThread.java:68)
	at ca.afroman.thread.DynamicThread$1.run(DynamicThread.java:55)
[2016-11-21/23:37:20] [Client/Game] [WARNING] I/O exception while completing keys (An established connection was aborted by the software in your host machine)
java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:33)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:69)
	at sun.nio.ch.IOUtil.write(IOUtil.java:40)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:336)
	at ca.afroman.network.TCPSocketChannel.write(TCPSocketChannel.java:99)
	at ca.afroman.game.SocketManager.keyCheck(SocketManager.java:558)
	at ca.afroman.game.Game.tick(Game.java:203)
	at ca.afroman.client.ClientGame.tick(ClientGame.java:1183)
	at ca.afroman.thread.DynamicTickRenderThread.onRun(DynamicTickRenderThread.java:36)
	at ca.afroman.thread.DynamicThread.dynamicRun(DynamicThread.java:68)
	at ca.afroman.thread.DynamicThread$1.run(DynamicThread.java:55)
[2016-11-21/23:38:27] [Client/Game] [DEBUG] Stopping Thread
[2016-11-21/23:38:27] [Client/Send] [DEBUG] [127.0.0.1:2143] PLAYER_DISCONNECT
[2016-11-21/23:38:27] [Client/Receive(127.0.0.1:2143)] [DEBUG] Stopping Thread[2016-11-21/23:38:27] [Client/Receive] [CRITICAL] Port is unreachable: 2143 (ICMP Port Unreachable)
[2016-11-21/23:38:27] [Client/Receive] [DEBUG] Stopping Thread
java.net.PortUnreachableException: ICMP Port Unreachable
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
[2016-11-21/23:38:27] [Client/Send] [DEBUG] Stopping Thread

	at java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:145)
	at java.net.DatagramSocket.receive(DatagramSocket.java:725)
	at ca.afroman.game.PacketReceiver.onRun(PacketReceiver.java:45)
	at ca.afroman.thread.DynamicThread.dynamicRun(DynamicThread.java:68)
	at ca.afroman.thread.DynamicThread$1.run(DynamicThread.java:55)

**Comment by CardboardBread** [comment]
read is when a socket receives data + what its sending
write is when a socket sends data + what its sending
get is when the getReceived is called, returning data to the TCPReceiver

**Comment by CardboardBread** [comment]
it seems that the game send the start_server packet, and it arrives, but the game doesn't actually do anything, as if no TCP data was parsed

**Comment by CardboardBread** [comment]
also the I/O exception while completing keys is because the sockets close by themselves, but their keys aren't cancelled

**Comment by defaultsamson** [comment]
Closing due to abandonment of the [socketchannel](https://github.com/qwertysam/afroman-client/tree/socketchannel) branch.
