### ISSUE TITLE
Datagram Sockets are not stopped when the game closes a connection

### ISSUE THREAD

**Issue by CardboardBread** [qwertysam/afroman-client#23]
[2016-11-25/23:24:00] [Client/Receive(192.168.56.1:2143)] [DEBUG] Stopping Thread
[2016-11-25/23:24:00] [Client/Receive] [DEBUG] Stopping Thread
[2016-11-25/23:24:00] [Client/Send] [DEBUG] Stopping Thread
java.net.SocketException: socket closed
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:145)
	at java.net.DatagramSocket.receive(DatagramSocket.java:725)
	at ca.afroman.game.PacketReceiver.onRun(PacketReceiver.java:45)
	at ca.afroman.thread.DynamicThread.dynamicRun(DynamicThread.java:68)
	at ca.afroman.thread.DynamicThread$1.run(DynamicThread.java:55)

**Comment by defaultsamson** [comment]
Fixed in 09b22d8357b4a95388d100387ed1ddbb398f5553 and 4664a199e07c3b79e45abf2adfd36355437060b1

[2017-00-01/11:39:42] [Client/Game] [DEBUG] Game loaded. Took 0.468 seconds
[2017-00-01/11:39:42] [Client/Game] [DEBUG] Starting Thread
[2017-00-01/11:39:45] [Client/Server/Receive] [DEBUG] Starting Thread
[2017-00-01/11:39:45] [Client/Server/Send] [DEBUG] Starting Thread
[2017-00-01/11:39:45] [Client/Server/Game] [DEBUG] Server connected on 127.0.0.1:2143
[2017-00-01/11:39:45] [Client/Server/Game] [DEBUG] Starting Thread
[2017-00-01/11:39:45] [Client/Receive] [DEBUG] Starting Thread
[2017-00-01/11:39:45] [Client/Send] [DEBUG] Starting Thread
[2017-00-01/11:39:45] [Client/Receive(127.0.0.1:2143)] [DEBUG] Starting Thread
[2017-00-01/11:39:45] [Client/Server/Receive(127.0.0.1:46620)] [DEBUG] Starting Thread
[2017-00-01/11:40:11] [Client/Server/Game] [DEBUG] Stopping Thread
**[2017-00-01/11:40:11] [Client/Receive(127.0.0.1:2143)] [DEBUG] Stopping Thread
[2017-00-01/11:40:11] [Client/Receive] [DEBUG] Stopping Thread
[2017-00-01/11:40:11] [Client/Send] [DEBUG] Stopping Thread**
[2017-00-01/11:40:11] [Client/Server/Receive(127.0.0.1:46620)] [DEBUG] Stopping Thread
[2017-00-01/11:40:11] [Client/Server/Receive] [DEBUG] Stopping Thread
[2017-00-01/11:40:11] [Client/Server/Send] [DEBUG] Stopping Thread
