### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by CardboardBread** [qwertysam/afroman-client#5]
java.io.FileNotFoundException: This is not a jar file: 
/C:/Users/mike_/Documents/GitHub/afroman-client/bin/ca/afroman/client/ClientGame.class
    at ca.afroman.util.FileUtil.getRunningJar(FileUtil.java:103)
    at ca.afroman.client.ClientGame.onStart(ClientGame.java:459)
    at ca.afroman.thread.DynamicThread.start(DynamicThread.java:149)
    at ca.afroman.thread.DynamicThread.startThis(DynamicThread.java:166)
    at ca.afroman.client.ClientGame.main(ClientGame.java:133)

appears after game has loaded

**Comment by defaultsamson** [comment]
This is caused from running the code from an IDE because the classes are loaded from the _bin_ directory, and not an individual jar or exe file.

**Comment by CardboardBread** [comment]
nvm laad
